# Generated by Django 3.1.4 on 2020-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/about/', verbose_name='image')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'AboutUsPage',
                'verbose_name_plural': 'AboutUsPage',
            },
        ),
    ]
