# Generated by Django 3.1.4 on 2020-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='header_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='header title'),
        ),
    ]
