# Generated by Django 3.1.4 on 2020-12-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutuspage_header_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tag', models.CharField(max_length=450, verbose_name='SEO Meta Tag')),
            ],
            options={
                'verbose_name': 'Meta tag',
                'verbose_name_plural': 'Meta tags',
            },
        ),
    ]
