# Generated by Django 3.1.4 on 2020-12-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_seometa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='main title')),
                ('header_title', models.CharField(max_length=200, verbose_name='second title')),
                ('image', models.ImageField(upload_to='pages/about/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
        ),
    ]
