# Generated by Django 3.1.4 on 2020-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.ImageField(upload_to='pages/headers/', verbose_name='image'),
        ),
    ]
