# Generated by Django 3.1.4 on 2020-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_blogheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='main title')),
                ('header_title', models.CharField(max_length=200, verbose_name='second title')),
                ('video', models.FileField(upload_to='headers')),
            ],
            options={
                'verbose_name': 'HomeHeader',
                'verbose_name_plural': 'HomeHeader',
            },
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
