# Generated by Django 3.1.4 on 2020-12-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201216_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='image',
            field=models.ImageField(upload_to='pages/about/', verbose_name='image'),
        ),
    ]
