# Generated by Django 3.1.4 on 2020-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201216_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='main title')),
                ('header_title', models.CharField(max_length=200, verbose_name='second title')),
                ('image', models.ImageField(upload_to='pages/blog/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'SocialHeader',
                'verbose_name_plural': 'SocialHeader',
            },
        ),
    ]
