# Generated by Django 3.1.2 on 2021-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210109_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
