# Generated by Django 3.1.2 on 2021-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_member_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
