# Generated by Django 3.1.4 on 2021-01-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_member_about'),
        ('pages', '0020_auto_20210110_1342'),
    ]

    operations = [
    ]
