# Generated by Django 3.1.4 on 2021-01-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_merge_20210111_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAlerts',
        ),
    ]
