# Generated by Django 3.1.5 on 2021-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_delete_emailalerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='company',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
