# Generated by Django 3.1.5 on 2021-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_enquiry_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='company',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
