# Generated by Django 3.1.5 on 2021-04-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20210404_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='company',
        ),
    ]
