# Generated by Django 3.1.4 on 2020-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together={('id', 'slug')},
        ),
    ]
