# Generated by Django 3.1.4 on 2020-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201212_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_value',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='show this post on homepage ?', verbose_name='featured'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_tag',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='SEO Meta Tag'),
        ),
    ]
