# Generated by Django 3.1.4 on 2020-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201215_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='small brief'),
        ),
    ]
